name       : bdwgc
version    : 8.2.2
release    : 16
source     :
    - https://github.com/ivmai/bdwgc/archive/v8.2.2.tar.gz : c9f74ff8fbc7276f3615fa72c6e808d63fe453d135b89dbf88c126e45424cfcf
homepage   : http://www.hpl.hp.com/personal/Hans_Boehm/gc
license    :
    - GPL-2.0-only
    - MIT
component  : programming.tools
emul32     : yes
summary    : Boehm-Demer-Weiser Garbage Collector
description: |
    Boehm-Demers-Weiser conservative garbage collector can be used as a garbage colecting replacement for C malloc or C++ new. It allows you to allocate memory basically as you normally would, without explicitly deallocating memory that is no longer useful. The collector automatically recycles memory when it determines that it can no longer be otherwise accessed.
setup      : |
    %reconfigure --disable-static --enable-cplusplus
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 doc/gc.man $installdir/usr/share/man/manman/gc.man
    rm -rf $installdir/usr/share/gc
