name       : bdwgc
version    : 7.6.4
release    : 10
source     :
    - http://www.hboehm.info/gc/gc_source/gc-7.6.4.tar.gz : b94c1f2535f98354811ee644dccab6e84a0cf73e477ca03fb5a3758fb1fecd1c
    - http://www.hboehm.info/gc/gc_source/libatomic_ops-7.6.2.tar.gz : 219724edad3d580d4d37b22e1d7cb52f0006d282d26a9b8681b560a625142ee6
homepage   : http://www.hpl.hp.com/personal/Hans_Boehm/gc
license    :
    - GPL-2.0-only
    - MIT
component  : programming.tools
emul32     : yes
summary    : Boehm-Demer-Weiser Garbage Collector
description: |
    Boehm-Demers-Weiser conservative garbage collector can be used as a garbage colecting replacement for C malloc or C++ new. It allows you to allocate memory basically as you normally would, without explicitly deallocating memory that is no longer useful. The collector automatically recycles memory when it determines that it can no longer be otherwise accessed.
setup      : |
    tar xf $sources/libatomic_ops-7.6.2.tar.gz
    ln -s libatomic_ops-7.6.2 libatomic_ops
    %configure --disable-static --enable-cplusplus
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 doc/gc.man $installdir/usr/share/man/manman/gc.man
    rm -rf $installdir/usr/share/gc
